In [21]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [18]:
my_series = [0,1,2,3]
my_index = ["A", "B", "C", "E"]
my_var2 = pd.Series(my_series, my_index)
my_var2
my_var2["E"]

3

In [19]:
cars = {"Tesla":12, "Mercedes": 42, "BMW":3}
my_var3 = pd.Series(cars)
my_var3

Tesla       12
Mercedes    42
BMW          3
dtype: int64

In [43]:
my_data = randn(4,3) #Rows, Columns
my_rows = ["A", "B", "C", "D"]
my_cols = ["Mon", "Tues", "Fri"]
my_df = pd.DataFrame(data=my_data, index=my_index, columns=my_cols)
my_df

        Mon      Tues       Fri
A -1.093387 -0.516363  0.608802
B -0.526924 -0.602921  1.859148
C -1.624818 -0.482643 -0.742064
E  0.029586  0.096867  0.985117

In [44]:
my_df2 = pd.read_csv('../datasets/zillow_hvi_1_bedroom.csv')
my_df2

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2023-04-30,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31
0,9,0,California,state,NaN,112658.703951,113071.670373,113640.455560,114923.039932,116466.240664,...,475371.867921,476232.474749,478611.237910,481800.780190,485604.700676,489670.378347,492881.877780,495286.122676,495870.662792,495414.278719
1,54,1,Texas,state,NaN,65536.244905,65639.826516,65681.137043,65645.806516,65553.089911,...,153207.274052,153473.559498,153888.087712,154210.423679,154642.400540,154854.620372,154808.007057,154670.748290,154310.590255,154094.818545
2,14,2,Florida,state,NaN,50540.747360,50649.942760,50772.576396,51050.360288,51347.463760,...,205468.254197,206135.838761,207110.304724,208072.617784,208952.774847,209325.678377,209505.118181,209882.644010,210051.218607,210076.354385
3,43,3,New York,state,NaN,128208.601118,128806.218919,129343.264130,130432.535615,131520.392142,...,373162.289111,373682.269544,374621.336988,375432.063905,376303.604869,376700.635000,376531.112357,376027.323424,375473.985133,375756.890615
4,47,4,Pennsylvania,state,NaN,58691.185281,58831.513149,58938.238970,59169.301694,59397.155781,...,157564.024056,158753.964885,160063.912505,161297.186953,162429.817128,163431.573684,164450.358128,165434.507268,166261.134346,166688.101426
5,21,5,Illinois,state,NaN,82572.443110,82667.946070,82933.003007,83530.645124,84275.301328,...,162130.257783,163666.438257,165230.090936,166692.219540,168390.748358,170172.903401,171798.804702,173083.361162,173655.785599,173846.575498
6,44,6,Ohio,state,NaN,50814.524141,50841.042937,50902.340411,51047.007696,51252.884098,...,102080.264080,103520.726298,104916.821319,106096.280342,107016.391017,107711.278596,108265.419829,108905.132173,109406.956403,109845.461370
7,16,7,Georgia,state,NaN,84618.284828,84941.343136,85269.557036,85990.674137,86725.350654,...,225615.246403,226647.818372,227644.627541,228743.067869,230261.896657,231908.724223,233102.175464,233658.310221,233367.743015,233060.278163
8,36,8,North Carolina,state,NaN,72515.816182,72744.050334,72982.938559,73371.560790,73664.429737,...,194717.496121,196446.726420,198404.283239,200111.170057,201612.605184,202871.531601,203818.360686,204814.708113,205323.800782,205662.557985
9,30,9,Michigan,state,NaN,68120.039162,68087.094910,68224.858345,68466.469902,68861.507651,...,148645.892945,149107.382679,150038.622630,151113.204755,152425.044041,153482.325056,154444.753439,155162.447299,155687.763639,155935.899958
10,40,10,New Jersey,state,NaN,88571.892493,88923.227066,89239.281082,89903.284282,90572.135307,...,262694.850578,264523.412128,266931.725804,269281.214629,271875.244912,274481.795491,277166.287642,279715.796331,281626.493308,283059.131328
11,56,11,Virginia,state,NaN,80679.721599,80496.445889,80611.431764,80883.606506,81289.008602,...,249580.427646,251405.564176,253876.238866,256072.898286,258228.060431,260094.804932,261521.767292,262876.735289,263431.987858,263984.656848
12,59,12,Washington,state,NaN,112508.050235,112786.464474,113171.383903,113863.387219,114618.195714,...,372791.219826,372550.060020,372971.162903,373221.127957,373759.734105,374254.476528,374680.124071,375127.178569,375168.910079,375492.962998
13,8,13,Arizona,state,NaN,64352.717997,64416.712539,64511.221883,64740.171722,65056.027031,...,224908.057973,224666.167772,225073.039065,225884.744860,227263.227311,228676.308457,229967.704917,231077.211687,231695.393912,231667.344018
14,26,14,Massachusetts,state,NaN,121663.570207,122169.008688,122750.868147,123924.153037,125112.538340,...,378306.593006,381524.597063,385306.613136,388788.980308,392055.767824,394837.986334,397030.137961,398730.114596,399953.206563,401373.819616
15,53,15,Tennessee,state,NaN,69499.548290,69555.650423,69670.260845,69900.861078,70162.077508,...,246265.786249,247624.245522,249194.184633,250343.825442,251160.386706,251673.356534,252171.637662,252684.350942,252534.880129,252180.612761
16,22,16,Indiana,state,NaN,NaN,NaN,NaN,NaN,NaN,...,104166.754331,105598.374226,106830.716120,107577.363448,108072.013689,108325.398369,108416.752760,108518.869029,108617.363151,108928.168712
17,27,17,Maryland,state,NaN,78694.190072,78596.641821,78548.224374,78504.248009,78676.780812,...,202532.998439,204037.881789,205609.407132,207212.568884,208812.715859,210299.438238,211396.084986,212400.191165,212724.244794,212928.772960
18,32,18,Missouri,state,NaN,49653.410549,49788.583945,49973.116476,50256.941429,50407.635213,...,112831.468259,113923.595412,114917.780754,115708.049915,116482.850708,117119.877200,117427.039972,117588.738805,117611.983923,117854.074046
19,60,19,Wisconsin,state,NaN,64231.222850,64237.772846,64265.223807,64330.029216,64457.758369,...,154744.158922,156422.567611,158110.282536,159598.003399,160863.723262,161899.110085,162637.061263,163234.287605,163542.525060,163863.083886
20,10,20,Colorado,state,NaN,95895.180206,96290.250935,96726.282349,97690.738463,98751.097323,...,321572.532938,321706.839454,322773.249563,323891.308177,324951.236140,325607.966896,325773.087394,325817.900039,325228.678806,324834.791375
21,31,21,Minnesota,state,NaN,62448.563864,62794.428599,63122.629667,63813.573520,64539.079437,...,174650.813125,174761.777856,175316.900769,176007.711885,176711.553260,177272.020655,177429.152710,177537.934108,177343.517288,177179.383921
22,51,22,South Carolina,state,NaN,83227.536953,83538.256635,83832.855579,84603.725769,85199.847190,...,195984.339277,197101.220505,198750.927043,200292.241426,201514.836682,202396.930934,202828.015865,203040.609913,202954.695472,203021.479430
23,4,23,Alabama,state,NaN,66568.713074,66576.341552,66653.910089,66853.448059,67135.720481,...,168291.865576,169710.928964,171014.846464,171951.391177,172256.006279,172349.235843,172214.195809,172171.039415,171920.470264,171723.777336
24,25,24,Louisiana,state,NaN,79238.655238,79120.489444,79197.835268,79478.587231,80012.716197,...,129244.337596,129494.687358,129299.382548,128766.473386,128030.551345,127283.077995,126522.660708,125943.631198,125234.840483,124312.732472
25,24,25,Kentucky,state,NaN,41809.215495,41861.579914,41896.435444,41981.943045,42054.920691,...,98993.422813,100441.016720,101778.696159,102870.036357,103640.289080,104156.876817,104487.842723,105126.094123,105873.432854,106604.041254
26,46,26,Oregon,state,NaN,87881.650807,88183.408502,88356.743303,88775.755859,89068.096813,...,297165.325246,298320.800426,299598.378707,300132.554384,300435.213672,300214.118275,299715.619311,299205.233244,298382.801040,297701.824090
27,45,27,Oklahoma,state,NaN,28994.427381,29010.821157,29051.089787,29106.409302,29224.309845,...,80089.225412,80811.670566,81449.259928,81730.393757,81795.443108,81861.202146,82052.310389,82679.747585,83231.011294,83592.970393
28,11,28,Connecticut,state,NaN,70675.598854,71065.408555,71155.375791,71451.152448,71688.194554,...,168190.119387,169866.657722,171871.433920,174456.564476,177346.829054,180075.272046,182347.066930,184295.531558,185763.955423,186806.777396
29,55,30,Utah,state,NaN,105589.926245,105680.399322,105800.277730,106087.310804,106821.562545,...,318098.035650,316733.773099,316720.966903,317025.743462,317457.743319,317614.758707,317817.938518,318241.188256,317910.269754,317595.194162
30,19,31,Iowa,state,NaN,55588.079285,55493.485320,55648.687477,55838.545877,56186.729917,...,96254.354270,97245.475455,98368.945300,99105.943438,99521.262411,99571.325224,99676.047871,99981.840898,100335.486613,100585.127980
31,42,32,Nevada,state,NaN,84268.876744,84294.107389,84335.400556,84504.202162,84747.708370,...,200041.211075,199246.151183,199172.066404,199861.369091,201158.795312,202313.202240,203436.904670,204584.641626,205726.386407,206501.582966
32,6,33,Arkansas,state,NaN,44679.393700,44695.322451,44720.197236,44717.362524,44783.314459,...,121650.750384,122852.128610,124169.196990,125117.499878,125408.800118,125364.264248,125256.007374,125506.787025,125755.563946,125973.915118
33,34,34,Mississippi,state,NaN,NaN,NaN,NaN,NaN,NaN,...,100015.189974,101098.179019,101940.338591,102399.072540,102662.999036,102861.087706,102948.129479,102912.966678,103038.347816,103116.319374
34,23,35,Kansas,state,NaN,43100.015238,43208.838845,43265.217254,43353.072518,43425.180507,...,67694.486942,68586.785006,69388.200552,69950.570520,70397.759251,70836.422683,71198.094505,71572.556006,71749.190953,71901.098394
35,41,36,New Mexico,state,NaN,NaN,NaN,NaN,NaN,NaN,...,193866.292147,196054.354824,197914.429011,199079.842989,199892.382722,200828.429768,201877.763815,202841.163222,203075.321593,203060.193394
36,38,37,Nebraska,state,NaN,53210.416439,53294.857368,53459.754795,53719.063156,53978.706887,...,122209.855093,123599.810511,124972.553377,125905.295066,126423.703862,126316.488553,126063.905468,125989.260194,126130.644201,126415.100237
37,20,38,Idaho,state,NaN,80825.973930,80770.597657,80968.788383,81138.500426,81435.178167,...,310296.702865,310689.159515,311986.739647,312878.826208,313962.440868,314833.988187,315207.359324,315039.168159,314423.218021,314181.994085
38,61,39,West Virginia,state,NaN,39221.385795,39166.486970,39155.845966,39105.114214,39126.219790,...,80172.314013,81720.396461,82604.873013,82965.865915,82891.719604,82925.064789,82962.825838,83277.975358,83531.084172,83973.490137
39,18,40,Hawaii,state,NaN,110063.709323,110131.560403,110365.637853,110770.251181,111473.931414,...,463354.086600,464978.083212,466314.886138,466962.988962,467169.552397,467627.612554,468070.871279,468417.454066,467718.021987,466666.720577
40,39,41,New Hampshire,state,NaN,57806.407664,58026.834241,58229.152338,58666.152049,59063.816838,...,215319.633352,217881.455547,220791.883123,223842.757209,227231.036609,230271.744755,232543.764258,233919.916708,234351.877343,234327.759887
41,28,42,Maine,state,NaN,66141.481359,66414.443239,66640.505727,67005.660584,67248.503628,...,239077.673052,242479.799202,246332.208575,249686.903619,252729.289390,255509.250238,257793.439547,259401.692990,260154.507061,260450.318187
42,50,43,Rhode Island,state,NaN,79119.937484,79614.026147,80061.487854,80982.604837,81871.243243,...,256041.614822,259125.187622,262655.527744,266089.816651,269241.807827,271841.080744,274124.194967,276096.620402,277969.223638,279405.285903
43,35,44,Montana,state,NaN,NaN,NaN,NaN,NaN,NaN,...,271035.508235,274531.743748,278432.581026,281018.869797,282350.160861,283206.528150,283750.852617,284055.474740,284097.716789,284510.305417
44,13,45,Delaware,state,NaN,59483.716672,59381.212870,59498.989868,59849.127081,60412.216551,...,163724.963124,164400.203944,164837.788518,165274.073151,166169.212469,167498.108271,169096.851905,171026.768910,172841.139833,173708.510400
45,52,46,South Dakota,state,NaN,NaN,NaN,NaN,NaN,NaN,...,140294.066130,141349.351132,142402.405720,143007.071132,143221.104714,143058.941280,143091.149973,143404.448471,143686.061201,143964.099964
46,37,47,North Dakota,state,NaN,NaN,NaN,NaN,NaN,NaN,...,110420.720127,110948.938742,111811.669156,112517.748931,113028.841361,113129.734481,113167.828037,113355.608515,113463.761631,113625.244007
47,3,48,Alaska,state,NaN,81310.639504,80419.761984,80480.449461,79799.206525,79666.469861,...,169070.638778,168700.560491,169572.202320,170740.239688,172156.727984,172753.001441,173211.424700,173095.511124,172515.640677,172300.267546
48,12,49,District of Columbia,state,NaN,111002.204886,111577.575530,112489.483113,114359.811970,116457.816191,...,387982.956839,387988.675034,389021.139649,391263.878251,393876.739178,396284.663806,397671.228952,397731.191366,396730.898484,395451.175018
49,58,50,Vermont,state,NaN,61425.997991,61627.486896,61768.112229,62049.031292,62199.648855,...,222910.601712,224835.761378,227273.321131,229598.226407,231839.750915,233661.480941,235074.007031,235781.865260,235596.406724,235477.434500
50,62,51,Wyoming,state,NaN,NaN,NaN,NaN,NaN,NaN,...,213881.683204,215241.476789,216912.650311,217933.055340,218811.623250,219533.080427,219829.156937,219641.708666,219077.400719,218927.484060

In [47]:
my_df2.loc[[0, 5]]
# my_df2.loc[0]

RegionID                  9
SizeRank                  0
RegionName       California
RegionType            state
StateName               NaN
                  ...
2023-09-30    489670.378347
2023-10-31     492881.87778
2023-11-30    495286.122676
2023-12-31    495870.662792
2024-01-31    495414.278719
Name: 0, Length: 294, dtype: object